### ISSUE TITLE
ESLint couldn't find the config "plugin:@typescript-eslint/stylistic" to extend from

### ISSUE THREAD

**Issue by ShadiestGoat** [dmitmel/eslint-config-dmitmel#8]
When  trying to use eslint with the typescript addong I get the following error (abbreviated):

```
ESLint: 8.49.0

ESLint couldn't find the config "plugin:@typescript-eslint/stylistic" to extend from. Please check that the name of the config is correct.

The config "plugin:@typescript-eslint/stylistic" was referenced from the config file in "PROJECT_NODE_MODULES/.pnpm/github.com+dmitmel+eslint-config-dmitmel@d97129ec35235415c6ae6a42299f55cdbb5d75fd_eslint@8.49.0/node_modules/eslint-config-dmitmel/presets/typescript-addon.js".
```

Cheers!

**Comment by ShadiestGoat** [comment]
I'll leave the issue open for now because further action might need to be taken on this repo (like adding the `@typescript-eslint/eslint-plugin` dependency), but when upgrading the parent repo's `@typescript-eslint/eslint-plugin` to latest version, it seemed to have resolved things.

**Comment by dmitmel** [comment]
Why has this crap suddenly become a thing that just everyone uses in the discord tinkering space?

**Comment by dmitmel** [comment]
Proposed fix:
```
pnpm remove eslint-config-dmitmel
```

**Comment by SomeAspy** [comment]
Updating the following fixed this issue
`@typescript-eslint/eslint-plugin` to `7.10.0` (latest as of writing)
`@typescript-eslint/parser` to `7.10.0` (latest as of writing)
`eslint` to `8.57.0`
